#!/bin/bash

source /opt/openfoam220/etc/bashrc

if [ ! -d ./0 ]
then
    cp -r 0_org 0
    blockMesh
    setFields > setFields.log
    funkySetFields -time 0 > funkySetFields.log
    echo "Running phaseFieldFoam ..."
    phaseFieldFoam > phaseField.log
else
    blockMesh
    echo "Running phaseFieldFoam ..."
    phaseFieldFoam > phaseField.log
fi

